version: '3'

services:

  pdb-1:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    expose:
      - "5432"

    ports:
      - '5432:5432'

    volumes:
      - pgdata-1:/var/lib/postgresql/data/

#  redis-1:
#    restart: always
#    image: redis:6
#
#    expose:
#      - "6379"
#
#    ports:
#      - "6379:6379"
#
#    volumes:
#      - redis-1:/data

volumes:
  pgdata-1:
#  redis-1:
